server:
  name: "antre-app"
  http:
    address: ":9999"
  debug: 0
  url: "http://localhost:9999"

toggle:
  enable_something: true

route_roles:
  "":
    roles:
      - id: 1
        name: "Developer"
      - id: 2
        name: "Admin"
      - id: 3
        name: "Customer"
      - id: 4
        name: "PIC"
      - id: 5
        name: "Owner"
      - id: 6
        name: "User"

  "PUT /v1/user/assign/{role}":
    roles:
      - id: 1
        name: "Developer"
      - id: 2
        name: "Admin"
      - id: 3
        name: "Customer"
      - id: 4
        name: "PIC"
      - id: 5
        name: "Owner"
      - id: 6
        name: "User"

  "POST /v1/reservations/{id}":
    roles:
      - id: 1
        name: "Developer"
      - id: 2
        name: "Admin"
      - id: 3
        name: "Customer"
      - id: 4
        name: "PIC"
      - id: 5
        name: "Owner"
      